# Start from official lightweight Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app
# Install system dependencies for building Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*


# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose FastAPI’s port
EXPOSE 8000

# Use Gunicorn with Uvicorn workers
CMD ["gunicorn",  "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]
