import { Helmet } from "react-helmet-async";

const SITE_ORIGIN = "https://wordwizai.com";

/**
 * Social preview card, generated by scripts/make-og-image.mjs into
 * public/og-image.png (npm run og:image).
 *
 * This must point at a file that actually ships. The catch-all SPA rewrite
 * returns index.html with a 200 for any missing path, so a wrong filename
 * here serves crawlers HTML labelled as a PNG rather than a clean 404.
 */
export const DEFAULT_OG_IMAGE = `${SITE_ORIGIN}/og-image.png`;

interface SeoHeadProps {
  /** Full <title> text for this page. Must be unique per route. */
  title: string;
  /** Meta description. Must be unique per route. */
  description: string;
  /** Route path, e.g. "/about". Combined with the site origin for canonical. */
  canonicalPath: string;
  ogType?: "website" | "article";
  /**
   * Absolute URL of a real social preview image (1200x630).
   *
   * Deliberately has no default. The catch-all SPA rewrite returns index.html
   * with a 200 for any missing path, so pointing at an image that doesn't
   * exist serves crawlers HTML labelled as a PNG — a broken preview that looks
   * like a successful response. Omitting the tag is the honest state until a
   * real image ships.
   */
  ogImage?: string;
  /** JSON-LD object or array of objects. */
  structuredData?: unknown;
}

/**
 * Per-page meta tags for routes that don't go through ArticlePageTemplate or
 * ComparisonPageTemplate.
 *
 * Without this, a route inherits whatever is hardcoded in index.html, which
 * means its title, description and canonical all point at the homepage — so
 * search engines treat the page as a duplicate of "/" and drop it.
 */
const SeoHead = ({
  title,
  description,
  canonicalPath,
  ogType = "website",
  ogImage = DEFAULT_OG_IMAGE,
  structuredData,
}: SeoHeadProps) => {
  const canonicalUrl = `${SITE_ORIGIN}${canonicalPath === "/" ? "/" : canonicalPath}`;

  return (
    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
      <link rel="canonical" href={canonicalUrl} />

      <meta property="og:type" content={ogType} />
      <meta property="og:url" content={canonicalUrl} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      {ogImage ? <meta property="og:image" content={ogImage} /> : null}

      <meta
        name="twitter:card"
        content={ogImage ? "summary_large_image" : "summary"}
      />
      <meta name="twitter:url" content={canonicalUrl} />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      {ogImage ? <meta name="twitter:image" content={ogImage} /> : null}

      {structuredData ? (
        <script type="application/ld+json">
          {JSON.stringify(structuredData)}
        </script>
      ) : null}
    </Helmet>
  );
};

export default SeoHead;
