"""Export the practice-word sentences that the guest "try it" route accepts.

The public /guest/analyze-audio route only scores sentences that appear on
the site's practice-word pages, so it can't be used as a free general-purpose
speech recognizer. Those sentences live in the frontend data file, which the
backend container never sees, so this script copies them into
backend/data/guest_sentences.json.

Run it after editing sampleSentences in frontend/src/data/phonicsPatterns.ts,
then redeploy the backend:

    python scripts/export_guest_sentences.py          # rewrite the JSON
    python scripts/export_guest_sentences.py --check  # exit 1 if it's stale

tests/test_guest_router.py runs the --check comparison, so a stale file fails
the backend tests rather than surfacing as "sentence not available" on the
live site.
"""

import json
import re
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
SOURCE = BACKEND_DIR.parent / "frontend" / "src" / "data" / "phonicsPatterns.ts"
TARGET = BACKEND_DIR / "data" / "guest_sentences.json"

_BLOCK = re.compile(r'^\s*slug:\s*"([^"]+)"(.*?)^\s*relatedSlugs:', re.M | re.S)
_SENTENCES = re.compile(r"sampleSentences:\s*\[(.*?)\]", re.S)
_STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def extract(source_text: str) -> dict[str, list[str]]:
    """Map each pattern slug to its sample sentences, in file order."""
    patterns: dict[str, list[str]] = {}
    for slug, body in _BLOCK.findall(source_text):
        match = _SENTENCES.search(body)
        if not match:
            raise ValueError(f"{slug} has no sampleSentences")
        sentences = [json.loads(f'"{s}"') for s in _STRING.findall(match.group(1))]
        if not sentences:
            raise ValueError(f"{slug} has an empty sampleSentences list")
        patterns[slug] = sentences
    if not patterns:
        raise ValueError(f"No patterns found in {SOURCE}")
    return patterns


def build() -> dict:
    return {
        "source": "frontend/src/data/phonicsPatterns.ts",
        "note": "Generated by backend/scripts/export_guest_sentences.py. Do not edit by hand.",
        "patterns": extract(SOURCE.read_text(encoding="utf-8")),
    }


def main() -> int:
    data = build()
    rendered = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        # git may check the file out with CRLF endings on Windows.
        if current.replace("\r\n", "\n") != rendered:
            print(f"{TARGET} is stale. Run: python scripts/export_guest_sentences.py")
            return 1
        print(f"{TARGET} is up to date ({len(data['patterns'])} patterns).")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    total = sum(len(v) for v in data["patterns"].values())
    print(f"Wrote {TARGET} ({len(data['patterns'])} patterns, {total} sentences).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
