import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const projectRoot = join(__dirname, "..");
const distPath = join(projectRoot, "dist");
const appTsxPath = join(projectRoot, "src", "App.tsx");

const SITE_ORIGIN = "https://wordwizai.com";

/**
 * Routes that must never be prerendered: the authenticated app surface,
 * auth flows, and dev-only pages. These need JS anyway and have no SEO value.
 *
 * Matched on whole path segments, so "/practice-words/short-a" is NOT
 * excluded by the "/practice" entry.
 */
const EXCLUDED_ROUTES = [
  "/dashboard",
  "/practice",
  "/settings",
  "/classes",
  "/progress",
  "/login",
  "/signup",
  "/oauth-callback",
  "/toast-test",
];

/**
 * Route families generated from a data module rather than declared one-by-one
 * in App.tsx. App.tsx carries a single dynamic route (e.g. "/practice-words/:slug");
 * each slug in the data file becomes its own static prerendered page.
 */
const PROGRAMMATIC_ROUTES = [
  { prefix: "/practice-words/", dataFile: "src/data/phonicsPatterns.ts" },
];

function expandProgrammaticRoutes() {
  const routes = [];

  for (const { prefix, dataFile } of PROGRAMMATIC_ROUTES) {
    const path = join(projectRoot, dataFile);
    if (!existsSync(path)) {
      throw new Error(`Programmatic route source not found: ${dataFile}`);
    }

    const source = readFileSync(path, "utf-8");
    // Anchored so "relatedSlugs: [...]" can't match.
    const slugs = [...source.matchAll(/^\s*slug:\s*"([^"]+)"/gm)].map((m) => m[1]);

    if (slugs.length === 0) {
      throw new Error(`No slugs found in ${dataFile}`);
    }

    const duplicates = slugs.filter((s, i) => slugs.indexOf(s) !== i);
    if (duplicates.length > 0) {
      throw new Error(
        `Duplicate slugs in ${dataFile}: ${[...new Set(duplicates)].join(", ")}`
      );
    }

    // relatedSlugs render as internal links on every generated page, so a
    // typo here ships a dead link. Cheaper to fail the build than to find it
    // in a crawl report months later.
    const known = new Set(slugs);
    const broken = new Set();
    for (const match of source.matchAll(/relatedSlugs:\s*\[([^\]]*)\]/g)) {
      for (const ref of match[1].matchAll(/"([^"]+)"/g)) {
        if (!known.has(ref[1])) broken.add(ref[1]);
      }
    }

    if (broken.size > 0) {
      throw new Error(
        `${dataFile} has relatedSlugs pointing at patterns that don't exist: ` +
          `${[...broken].join(", ")}`
      );
    }

    routes.push(...slugs.map((slug) => `${prefix}${slug}`));
  }

  return routes;
}

/**
 * Discover every prerenderable route straight from App.tsx.
 *
 * This is deliberately derived rather than hand-listed: the previous version
 * of this script hardcoded 8 of 40 routes and silently went stale every time
 * a new SEO page was added. Any new content route now prerenders for free.
 */
function discoverRoutes() {
  const source = readFileSync(appTsxPath, "utf-8");
  const found = new Set();

  for (const match of source.matchAll(/path="([^"]+)"/g)) {
    found.add(match[1]);
  }

  const routes = [...found]
    // Drops the "*" catch-all.
    .filter((route) => route.startsWith("/"))
    // Drops parameterized routes like "/practice/:sessionId".
    .filter((route) => !route.includes(":"))
    .filter(
      (route) =>
        !EXCLUDED_ROUTES.some(
          (excluded) => route === excluded || route.startsWith(`${excluded}/`)
        )
    )
    .concat(expandProgrammaticRoutes())
    .sort();

  if (routes.length === 0) {
    throw new Error(
      `No prerenderable routes found in ${appTsxPath}. Has the Route syntax changed?`
    );
  }

  return [...new Set(routes)];
}

/**
 * Generate sitemap.xml from the routes actually prerendered.
 *
 * Previously hand-maintained, which meant it drifted: /privacy was missing
 * entirely while /login and /signup were listed despite being auth pages.
 * Deriving it from the same list that produces the HTML makes that
 * impossible.
 */
function writeSitemap(pages, distPath) {
  const today = new Date().toISOString().slice(0, 10);

  const priorityFor = (route) => {
    if (route === "/") return "1.0";
    if (route === "/practice-words") return "0.9";
    if (route === "/privacy") return "0.3";
    if (route === "/about" || route === "/contact") return "0.6";
    return "0.8";
  };

  const body = pages
    .map(({ route }) => {
      const loc = route === "/" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${route}`;
      return [
        "  <url>",
        `    <loc>${loc}</loc>`,
        `    <lastmod>${today}</lastmod>`,
        `    <priority>${priorityFor(route)}</priority>`,
        "  </url>",
      ].join("\n");
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/prerender.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

  writeFileSync(join(distPath, "sitemap.xml"), xml, "utf-8");
  return pages.length;
}

// HTML comments can legitimately mention tag names (index.html documents why
// no <title> or canonical belongs there), so strip them before counting tags.
const stripComments = (html) => html.replace(/<!--[\s\S]*?-->/g, "");

const firstMatch = (html, pattern) => {
  const match = html.match(pattern);
  return match ? match[1].trim().replace(/\s+/g, " ") : null;
};

const titleOf = (html) => firstMatch(html, /<title[^>]*>([\s\S]*?)<\/title>/i);

const titleCountOf = (html) => (html.match(/<title[^>]*>/gi) || []).length;

const canonicalsOf = (html) =>
  [...html.matchAll(/<link[^>]*rel="canonical"[^>]*>/gi)].map((m) =>
    firstMatch(m[0], /href="([^"]*)"/i)
  );

const descriptionsOf = (html) =>
  [...html.matchAll(/<meta[^>]*name="description"[^>]*>/gi)].map((m) =>
    firstMatch(m[0], /content="([^"]*)"/i)
  );

/**
 * The build gate. Every problem found here is one that would otherwise ship
 * silently and cost organic traffic for months, so these are errors, not warnings.
 */
function validate(pages) {
  const homepage = pages.find((page) => page.route === "/");
  const problems = [];

  for (const { route, html: rawHtml } of pages) {
    const html = stripComments(rawHtml);
    const title = titleOf(html);
    const canonicals = canonicalsOf(html);
    const descriptions = descriptionsOf(html);
    const expectedCanonical = route === "/" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${route}`;

    if (!title) {
      problems.push(`${route} — no <title> in prerendered output`);
    } else if (titleCountOf(html) > 1) {
      problems.push(
        `${route} — ${titleCountOf(
          html
        )} <title> tags. Remove the hardcoded one from index.html or the duplicate Helmet block from the page.`
      );
    }

    if (canonicals.length === 0) {
      problems.push(`${route} — no <link rel="canonical">`);
    } else if (canonicals.length > 1) {
      problems.push(
        `${route} — ${canonicals.length} canonical tags (${canonicals.join(
          ", "
        )}). Search engines will ignore all of them. Remove the hardcoded one from index.html.`
      );
    } else if (canonicals[0].replace(/\/$/, "") !== expectedCanonical.replace(/\/$/, "")) {
      problems.push(
        `${route} — canonical points at ${canonicals[0]}, expected ${expectedCanonical}`
      );
    }

    if (descriptions.length > 1) {
      problems.push(`${route} — ${descriptions.length} meta descriptions, expected 1`);
    }

    if (
      route !== "/" &&
      homepage &&
      title &&
      title === titleOf(stripComments(homepage.html))
    ) {
      problems.push(
        `${route} — title is identical to the homepage ("${title}"). This page has no Helmet block.`
      );
    }

    if (!/<div id="root"[^>]*>\s*<[a-z]/i.test(html)) {
      problems.push(`${route} — #root is empty; the app did not render before capture`);
    }
  }

  return problems;
}

const SECTIONS = [
  ["/guides/", "Guides"],
  ["/comparisons/", "Comparisons"],
  ["/articles/", "Articles"],
];

const sectionFor = (route) =>
  SECTIONS.find(([prefix]) => route.startsWith(prefix))?.[1] ?? "Site";

// llms.txt is plain markdown, so HTML entities from the serialized DOM
// ("Phonics &amp; Pronunciation") need decoding back to their characters.
const decodeEntities = (text) =>
  text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&nbsp;/g, " ");

/**
 * Emit /llms.txt and /llms-full.txt.
 *
 * Both are generated from the pages just prerendered, so they cannot drift out
 * of sync with the site the way a hand-maintained file would. Answer engines
 * (ChatGPT, Claude, Perplexity) don't execute JavaScript, so these plus the
 * prerendered HTML are what make the content legible to them at all.
 */
function writeLlmsFiles(pages, distPath) {
  const entries = pages.map(({ route, html, text }) => {
    const clean = stripComments(html);
    return {
      route,
      section: sectionFor(route),
      title: decodeEntities(titleOf(clean) ?? route),
      description: decodeEntities(descriptionsOf(clean)[0] ?? ""),
      url: route === "/" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${route}`,
      text,
    };
  });

  const index = [
    "# Word Wiz AI",
    "",
    "> A free, browser-based AI reading tutor for children ages 5-8. A child reads a",
    "> sentence aloud; Word Wiz AI transcribes it at the phoneme level, compares it to",
    "> the expected pronunciation, and gives targeted feedback on the specific sounds",
    "> they missed. No subscription, no ads. Built around phonics rather than",
    "> whole-word memorization.",
    "",
    "The pages below are written for parents and teachers of beginning and struggling",
    "readers. Guides are instructional, comparisons evaluate other reading apps, and",
    "articles diagnose specific reading problems.",
    "",
  ];

  for (const [, section] of [...SECTIONS, ["", "Site"]]) {
    const inSection = entries.filter((entry) => entry.section === section);
    if (inSection.length === 0) continue;

    index.push(`## ${section}`, "");
    for (const entry of inSection.sort((a, b) => a.title.localeCompare(b.title))) {
      index.push(
        entry.description
          ? `- [${entry.title}](${entry.url}): ${entry.description}`
          : `- [${entry.title}](${entry.url})`
      );
    }
    index.push("");
  }

  writeFileSync(join(distPath, "llms.txt"), index.join("\n"), "utf-8");

  const full = [
    "# Word Wiz AI — full content",
    "",
    `Generated ${new Date().toISOString().slice(0, 10)} from ${entries.length} pages.`,
    "",
  ];

  for (const entry of entries) {
    full.push(
      "",
      "---",
      "",
      `# ${entry.title}`,
      `URL: ${entry.url}`,
      "",
      entry.text ?? "",
      ""
    );
  }

  writeFileSync(join(distPath, "llms-full.txt"), full.join("\n"), "utf-8");

  return {
    indexBytes: index.join("\n").length,
    fullBytes: full.join("\n").length,
  };
}

const BASE_ARGS = [
  "--no-sandbox",
  "--disable-setuid-sandbox",
  "--disable-dev-shm-usage",
];

/**
 * Launch a browser suitable for the environment we're building in.
 *
 * Locally, puppeteer's own bundled Chrome works. Vercel's build container is
 * minimal and ships none of Chrome's runtime shared libraries, so a plain
 * downloaded Chromium dies there with:
 *
 *   chrome: error while loading shared libraries: libnspr4.so: cannot open
 *   shared object file — Code: 127
 *
 * @sparticuz/chromium packages those libraries alongside the binary, which is
 * why it is used on Vercel specifically rather than everywhere (it is
 * Linux-only, so it cannot be the local path on macOS or Windows).
 *
 * Set PRERENDER_BROWSER=sparticuz to force that path on any other Linux CI,
 * or PUPPETEER_EXECUTABLE_PATH to point at a Chrome you supply yourself.
 */
async function launchBrowser() {
  const explicitPath = process.env.PUPPETEER_EXECUTABLE_PATH;
  const useSparticuz =
    process.env.PRERENDER_BROWSER === "sparticuz" ||
    (Boolean(process.env.VERCEL) && !explicitPath);

  if (explicitPath) {
    console.log(`Browser: PUPPETEER_EXECUTABLE_PATH -> ${explicitPath}`);
    const { default: puppeteerCore } = await import("puppeteer-core");
    return puppeteerCore.launch({
      executablePath: explicitPath,
      headless: true,
      args: BASE_ARGS,
    });
  }

  if (useSparticuz) {
    let chromium;
    let puppeteerCore;
    try {
      ({ default: chromium } = await import("@sparticuz/chromium"));
      ({ default: puppeteerCore } = await import("puppeteer-core"));
    } catch (error) {
      console.error(
        "This build needs @sparticuz/chromium and puppeteer-core, which are\n" +
          "not installed. Run in frontend/:\n" +
          "  npm install --save-dev @sparticuz/chromium puppeteer-core\n" +
          `(underlying error: ${error.message})`
      );
      process.exit(1);
    }

    const executablePath = await chromium.executablePath();
    console.log(`Browser: @sparticuz/chromium -> ${executablePath}`);

    return puppeteerCore.launch({
      executablePath,
      headless: true,
      args: [...new Set([...chromium.args, ...BASE_ARGS])],
    });
  }

  let puppeteer;
  try {
    ({ default: puppeteer } = await import("puppeteer"));
  } catch {
    console.error(
      'puppeteer is not installed. Run "npm install --save-dev puppeteer" in frontend/.'
    );
    process.exit(1);
  }

  console.log("Browser: puppeteer bundled Chrome");
  return puppeteer.launch({ headless: "new", args: BASE_ARGS });
}

async function prerender() {
  console.log("Starting prerender...\n");

  if (!existsSync(join(distPath, "index.html"))) {
    console.error(`No build found at ${distPath}. Run "vite build" first.`);
    process.exit(1);
  }

  const routes = discoverRoutes();
  console.log(`Discovered ${routes.length} routes from src/App.tsx\n`);

  const browser = await launchBrowser();

  const { preview } = await import("vite");
  const previewServer = await preview({
    preview: { port: 4173, strictPort: true },
    logLevel: "silent",
  });
  const baseUrl = "http://localhost:4173";

  // Captured in memory and written only after every route succeeds. Writing
  // during the loop would mutate dist/index.html mid-run, which is what the
  // preview server hands to every not-yet-prerendered route.
  const pages = [];

  try {
    for (const route of routes) {
      process.stdout.write(`  ${route} ... `);

      const page = await browser.newPage();
      await page.setUserAgent(
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      );

      try {
        await page.goto(`${baseUrl}${route}`, {
          waitUntil: "networkidle2",
          timeout: 45000,
        });
      } catch {
        // A hanging third-party request shouldn't fail the route; the render
        // check below is what actually decides whether the capture is usable.
        process.stdout.write("(load timeout) ");
      }

      await page.waitForSelector("#root > *", { timeout: 15000 });

      // react-helmet-async injects into <head> after the first paint, so wait
      // for the canonical tag rather than racing it with a fixed delay.
      await page
        .waitForFunction(
          () => document.querySelector('link[rel="canonical"]') !== null,
          { timeout: 10000 }
        )
        .catch(() => process.stdout.write("(no canonical) "));

      await new Promise((resolve) => setTimeout(resolve, 400));

      const html = (await page.content()).replace(
        '<div id="root"',
        '<div id="root" data-prerendered="true"'
      );

      // Readable text, used to build llms-full.txt.
      const text = await page.evaluate(() => {
        const scope =
          document.querySelector("article") ||
          document.querySelector("main") ||
          document.body;
        return scope.innerText.replace(/\n{3,}/g, "\n\n").trim();
      });

      pages.push({ route, html, text });
      await page.close();
      console.log("ok");
    }
  } finally {
    await browser.close();
    await previewServer.close?.();
  }

  console.log("\nValidating output...");
  const problems = validate(pages);

  if (problems.length > 0) {
    console.error(`\nPrerender validation failed (${problems.length} problems):\n`);
    for (const problem of problems) console.error(`  - ${problem}`);
    console.error("\nNothing was written. Fix the above and rebuild.\n");
    process.exit(1);
  }

  for (const { route, html } of pages) {
    const outputPath =
      route === "/"
        ? join(distPath, "index.html")
        : join(distPath, route, "index.html");

    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, html, "utf-8");
  }

  const llms = writeLlmsFiles(pages, distPath);
  const sitemapUrls = writeSitemap(pages, distPath);

  console.log(`Validation passed. Wrote ${pages.length} prerendered pages.`);
  console.log(
    `Wrote llms.txt (${(llms.indexBytes / 1024).toFixed(1)}kb), ` +
      `llms-full.txt (${(llms.fullBytes / 1024).toFixed(0)}kb) and ` +
      `sitemap.xml (${sitemapUrls} URLs).\n`
  );
}

prerender().catch((error) => {
  console.error("Prerender failed:", error);
  process.exit(1);
});
